# Generated by Django 3.2 on 2021-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='tr', max_length=5),
        ),
    ]
